### PR TITLE
MC 1.17 Support

### PR DESCRIPTION
**Pull request by Chris6ix**
Updated dependencies, everything else should be fine.
Just not sure tho if the update to Java 16 breaks compatibility with older MC versions, and I'm unable to test this currently.
If there are any problems with that, tell me and ill revert it back to Java 8 (Or you could drop support for ancient versions such as 1.8-1.12)

### CODE REVIEW

**Comment by benwoo1110** [comment]
Hi, thanks for the PR! I think Java 8 should still be supported as I suspect Java 16 won't work on older mc versions.

**Comment by Chris6ix** [comment]
Okay, should be ready now :)

**Review by benwoo1110 — APPROVED** [review]
Nice! Thank you for the PR!

**Comment by Chris6ix** [comment]
No problem :)

**Comment by benwoo1110** [comment]
Looks like it builds ok after some minor config change, if you want can get it from https://ci.benergy10.dev/job/FlyPerms/

**Pull request merged**
