### PR TITLE
Some improvements/updates

### PR DESCRIPTION
**Pull request by Chris6ix**
-Improved README (https://github.com/Chris6ix/FlyPerms/blob/Chris6ix-Some-Improvements/Updates/README.md to see how it looks)
-Updated to 1.17.1

Tell me how you like the new README!

### CODE REVIEW

**Comment by benwoo1110** [comment]
Look amazing, just one issue with the github logo not being very visible in dark theme
image

**Comment by Chris6ix** [comment]
Fixed :)

**Comment by Chris6ix** [comment]
Here is the preview : https://github.com/Chris6ix/FlyPerms/blob/Chris6ix-Some-Improvements/Updates/README.md

**Review by benwoo1110 — APPROVED** [review]
1.17.1 paper is so, so should be safe to merge. Thanks!

**Pull request merged**
