### PR TITLE
Small improvement in README

### PR DESCRIPTION
**Pull request by Chris6ix**
Improved Image loading on slower internet connections by using locally saved Images
This also cleans the code a little
Looks/Works just as the old one, just loads a little faster :)

I saw that the "features" category on Spigot is still the old one, so when you release the new version with WorldGuard support, you can add that info to it (Like here in the README)

If you want, you can also create a Contributors box on Flyperms Spigot page and add me to it :)
(Same Username as here)

### CODE REVIEW

**Review by benwoo1110 — APPROVED** [review]
Looks good. For spigot, the release will likely need some time. The worldguard feature is untested and I have other code change in mind.

**Comment by Chris6ix** [comment]
Alright, just add me to it when you release the update
If you want, then you can tell me what specifically you need tested with the WorldGuard feature :)

**Comment by benwoo1110** [comment]
Just whether allow fly based on worldguard region works or not loll. 

Also saw this from a pr you opened 👀:
image

**Comment by Chris6ix** [comment]
Yeah, that's from QuickShop, where I am also working on the README currently :)
Do you prefer this table style?
If so, then I could also bring it to the FlyPerms README...

**Comment by benwoo1110** [comment]
Yea HAHA, that looks better 🤩

**Comment by Chris6ix** [comment]
Okay 👍

**Pull request merged**
